services:
  redis:
    image: redis:7.4-alpine
    container_name: opencommotion-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: opencommotion-postgres
    environment:
      POSTGRES_USER: opencommotion
      POSTGRES_PASSWORD: opencommotion
      POSTGRES_DB: opencommotion
    ports:
      - "5432:5432"
    volumes:
      - opencommotion-postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  opencommotion-postgres:
